### PR TITLE
Update Befaco to v2.7.1

### PR DESCRIPTION
**Pull request by hemmer**
Adds Burst, Voltio and Octaves. Upstream PonyVCO has been made polyphonic (with SIMD) but CPU usage appears to be unchanged.

Burst panel graphics have been modified slightly for legibility (may do more of this type of work for other modules in future)!

PXL_20240830_095926433

### CODE REVIEW

**Comment by danngreen** [comment]
Ok, I figured out the Octaves crashing. There's dynamic allocation happening in the audio process(), which we can't have. Every once in a while the allocation takes longer than we have to process each block, and we get the crash.

It's this:
```
const std::vector<int> connectedOutputs = getConnectedOutputs();
```
I refactored this to not use allocations, and it runs without crashing now. There are probably a better way of doing the same thing, but I did it like this: https://github.com/hemmer/Befaco/compare/v2-mm...danngreen:Befaco:v2-mm

It's definitely a bug in MetaModule that using dynamic allocations crashes: it should just stop the audio loop and pop-up the "Audio exceeded 99%" notification. So I will make an issue for that. But we can't have dynamic allocations in process() anyways, since every once in a while it'll kill the audio no matter how small of an allocation.

Also, I profiled the Octave module and discovered the `simd::floor` call was terribly inefficient (I suppose it's just a difference between CA7 NEON and other SIMD?). So I replaced that, and CPU usage went from ~70-80% to 50-60%.

Finally if you want, you can revert the change to Muxlicer's jack names (adding In and Out), as I'm going to merge in a change to the vcv adaptor that append these strings automatically if "In" or "Input" is not found in the jack name (case-insensitive).

Everything else is good to merge!

**Comment by hemmer** [comment]
Wow that's a bit embarrassing, no dynamic allocations on the audio thread is DSP 101 :see_no_evil: . Thanks for catching will add to upstream too, what an unnecessary thing to have done!

As for simd::floor it's a common trick I learned in VCV, handy to deal with positive and negative phase increments, I think it pops up in a few plugins tbh. And while you can take steps to ensure phase increments are less than 1, this works even if they're not (though you probably have bigger aliasing problems if so!). I'll take a look at this and the pr as a whole later today hopefully. Thanks again for input! 

https://github.com/VCVRack/Fundamental/blob/v2/src%2FVCO.cpp#L72

**Comment by danngreen** [comment]
It looked so innocent, I read over the code so many times and didn't spot it either, until step-debugging plopped me into malloc.

Makes sense about using floor. I realize I need to fix my replacement function so that it handles negative floats correctly. Easy enough. It lives in the vcv adaptor layer so all vcv plugins will automatically take advantage of the neon-friendly version, and it should produce identical results for all cases.

**Comment by danngreen** [comment]
I

**Comment by danngreen** [comment]
Looks good. I'll merge

BTW, I'm reading back and realize I was being unclear about std::floor. I already implemented a NEON version for it, which is very efficient. The `simd::ifelse` that you used in the latest commit is equally efficient, so I'm fine to merge that in. But you could use simd::floor now to keep it closer to the non-VCV version.

**Comment by hemmer** [comment]
Ah ok great - let's keep as is (with ifelse). Feel free to merge!

**Pull request merged**
