### PR TITLE
Befaco v2.8.0: add Bandit (+bugfixes)

### PR DESCRIPTION
**Pull request by hemmer**
image

Bypass light button still not working, investigating

Have merged `ponyvco-safety-net` changes from danngreen/Befaco

### CODE REVIEW

**Comment by hemmer** [comment]
@danngreen - The bypass button acts either as a momentary (in gate mode) or latch (in latch mode). I'm not sure this is particularly easy to reproduce with MM API (basically requires live editing the `momentary = true/false` attribute, which is a widget state attribute). I'm sure I can re-write the relevant part of logic to be MM specific though.

**Comment by danngreen** [comment]
Sorry for the delay getting back to this -- November is a month of holidays and travels for me.

> The bypass button acts either as a momentary (in gate mode) or latch (in latch mode). I'm not sure this is particularly easy to reproduce with MM API (basically requires live editing the momentary = true/false attribute, which is a widget state attribute). I'm sure I can re-write the relevant part of logic to be MM specific though.

Yeah, this kind of dynamic element won't work well. 
But with v2.0, modules can modify the state of their own parameters, and the GUI will see those changes. So at least the button will display correctly (the correct svg frame will be drawn, and the arc will be in the correct position on the knobset view page) if your workaround involves the module setting the param value to 0 or 1 with `params[LAUNCH_MODE_PARAM].setValue()`

**Comment by hemmer** [comment]
OK no worries thanks. I wonder if it makes sense short term to just merge back Bandit (and a few other minor fixes), and think about Bypass when v2 is default firmware branch. Another option is short term have the module just use the gate input for bypassing (and disable button for now)?

**Comment by hemmer** [comment]
I've removed Bypass for now as I think it's better to merge back Bandit, and I can always revisit adding it later. Sound ok to you?

**Comment by danngreen** [comment]
Sounds good! I'll test it out and merge into main if it's all good

**Comment by danngreen** [comment]
Ok, checks out. Fairly low CPU usage, too.

**Pull request merged**
